# yaml-language-server: $schema=https://www.schemastore.org/codecov.json

codecov:
    branch: "main"
    max_report_age: "24h"
    notify:
        wait_for_ci: true
    require_ci_to_pass: true
    slug: "Nick2bad4u/typedoc-plugin-hash-link-references"

comment:
    behavior: "default"
    layout: "header, diff, flags, files, footer"
    require_base: false
    require_changes: false
    require_head: true

component_management:
    default_rules:
        statuses:
            - target: "auto"
              threshold: "2%"
              type: "project"
    individual_components:
        - component_id: "plugin_source"
          name: "Plugin source"
          paths:
              - "src/core.ts"
              - "src/plugin.ts"

coverage:
    precision: 2
    range: "60...100"
    round: "down"
    status:
        patch:
            default:
                target: "80%"
                threshold: "2%"
        project:
            default:
                target: "auto"
                threshold: "2%"

flags:
    os-linux:
        carryforward: true
        paths:
            - "src/"

    os-macos:
        carryforward: true
        paths:
            - "src/"

    os-windows:
        carryforward: true
        paths:
            - "src/"

ignore:
    - "coverage/**"
    - "dist/**"
    - "docs/**"
    - "scripts/**"
    - "test/**"
    - "**/*.d.ts"
    - "**/*.test.*"
    - "**/*.spec.*"
