import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars = {
    docs: [
        {
            className: "sb-doc-overview",
            id: "intro",
            label: "Overview",
            type: "doc",
        },
        {
            className: "sb-doc-getting-started",
            id: "getting-started",
            label: "Getting Started",
            type: "doc",
        },
        {
            className: "sb-cat-guides",
            collapsed: false,
            collapsible: true,
            items: ["configuration", "link-behavior"],
            label: "Guides",
            type: "category",
        },
        {
            className: "sb-cat-api-overview",
            collapsed: true,
            collapsible: true,
            items: [
                {
                    dirName: "developer/api",
                    type: "autogenerated",
                },
            ],
            label: "API Reference",
            link: {
                description:
                    "Generated TypeDoc API reference for the plugin entrypoint and core rewrite helpers.",
                title: "API Reference",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-developer",
            collapsed: true,
            collapsible: true,
            items: ["developer/index"],
            label: "Developer Notes",
            type: "category",
        },
    ],
} satisfies SidebarsConfig;

export default sidebars;
